ci: improve release workflow (#62)
(edited after most recent commit)

When the project was moved to the OP repo, the `release.yml` workflow
was updated so that releases are no longer published in draft state.
This means that releases happen automatically once a version-bump PR is
merged; however, the release notes do not include any summary in the
title (only a version number), and the release notes will be published
instantly without edits. While the release notes can always be manually
edited by a contributor after the fact, I don't think that's ideal.

This PR adds an npm script, `npm run release` that collects the
version-bump type, a release summary, and whether the release should be
in draft, and it stores that data and runs npm version to trigger a
version bump PR (replacing the need to run `npm version`). This also
updates the `release.yml` workflow to collect these attributes and
integrate them.

(Note: Because of the changes, merging this PR will trigger the release
workflow, even though I'm not intending to actually trigger a release.
Because there's no version bump, however, the worklow will exit
gracefully without doing a release. I do plan to PR a version bump since
it's been a month and there are some i18n/bugfix PRs that have been
merged since. But I'd prefer to land this first.)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -5,38 +5,37 @@ on:
     branches:
       - main
     paths:
-      - 'plugin/CactbotEventSource/Properties/AssemblyInfo.cs'
+      - 'package.json'
 
 jobs:
   validate_tag:
     runs-on: ubuntu-latest
     if: ${{ github.repository == 'OverlayPlugin/cactbot' }}
     outputs:
-      version: ${{ steps.determine_version.outputs.version }}
+      version: ${{ steps.get_version.outputs.version }}
+      do_release: ${{ steps.check_tag.outputs.do_release }}
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
-      - name: Determine Version
-        id: determine_version
-        shell: pwsh
-        run: |
-          $text = [System.IO.File]::ReadAllText("plugin/CactbotEventSource/Properties/AssemblyInfo.cs");
-          $regex = [regex]::New('\[assembly: AssemblyVersion\("([0-9]+\.[0-9]+\.[0-9]+)\.[0-9]+"\)');
-          $m = $regex.Match($text);
-          if (-not $m) {
-              echo "Error: Version number not found in the AssemblyInfo.cs!"
-              exit 1
-          }
-          $version = $m.Groups[1]
-          echo "::set-output name=version::$version"
+
+      - name: Get Project Version
+        id: get_version
+        uses: 'euberdeveloper/ga-project-version@main'
+
       - name: Check Tag Exists
+        id: check_tag
         shell: bash
         run: |
-          if [ $(git tag -l "v${{ steps.determine_version.outputs.version }}") ]; then
-              echo "Error: Existing git tag found. Exiting..."
-              exit 1
+          if [ "${{ steps.get_version.outputs.version }}" == "" ]; then
+            echo "Error: Unable to determine version from package.json"
+            exit 1
+          elif [ $(git tag -l "v${{ steps.get_version.outputs.version }}") ]; then
+              echo "No version bump - ${{ steps.get_version.outputs.version }}.  Skipping remaining jobs..."
+          else
+              echo "Version bump detected - ${{ steps.get_version.outputs.version }}"
+              echo "::set-output name=do_release::true"
           fi
 
   validate_versions:
@@ -54,7 +53,7 @@ jobs:
   create_release:
     runs-on: windows-latest
     needs: [validate_tag, validate_versions]
-    if: ${{ github.repository == 'OverlayPlugin/cactbot' }}
+    if: ${{ github.repository == 'OverlayPlugin/cactbot' }} && ${{ needs.validate_tag.outputs.do_release }}
     env:
       GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
     steps:
@@ -62,6 +61,7 @@ jobs:
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
+
       - name: Set up msbuild
         uses: microsoft/setup-msbuild@v1.0.2
 
@@ -75,11 +75,13 @@ jobs:
           key: ${{ runner.os }}-cactbot-${{ hashFiles('./util/fetch_deps.ts', './util/DEPS.json5') }}
           restore-keys: |
             ${{ runner.os }}-cactbot-
+
       - name: Fetch Dependencies
         if: steps.cache-dependencies.outputs.cache-hit != 'true'
         run: |
           npm run fetch-deps
         shell: bash
+
       - name: Build Cactbot Plugin
         shell: cmd
         run: |
@@ -88,27 +90,55 @@ jobs:
       - name: Build JavaScript UI Module Bundles
         run: |
           npm run build
+
       - name: Setup Staging Directory
         run: |
           ./util/publish.sh
         shell: bash
+
       - name: Create Release Artifact
         run: |
           mkdir cactbot
           mv publish/cactbot-release/cactbot/ cactbot
           compress-archive cactbot cactbot-${{ needs.validate_tag.outputs.version }}.zip
         shell: pwsh
+
       - name: Create Tag
         shell: bash
         run: git tag "v${{ needs.validate_tag.outputs.version }}" && git push --tags
+
+      - name: Fetch Release Attributes
+        id: fetch_attributes
+        uses: zoexx/github-action-json-file-properties@release
+        with:
+          file_path: "package.json"
+
+      - name: Set Release Attributes
+        id: set_attributes
+        shell: pwsh
+        run: |
+          $release_name = "${{ needs.validate_tag.outputs.version }}";
+          $release_draft = "false";
+          $release_summary = "${{steps.fetch_attributes.outputs.releaseSummary}}";
+          if ($release_summary) {
+              $release_name += ": " + $release_summary;
+          }
+          if ("${{steps.fetch_attributes.outputs.releaseInDraft}}" -eq "true") {
+              $release_draft = "true";
+          }
+          echo "Release Name: $release_name";
+          echo "Release as Draft: $release_draft";
+          echo "::set-output name=release_name::$release_name"
+          echo "::set-output name=release_draft::$release_draft"
+
       - name: Create Release
         uses: ncipollo/release-action@v1
         with:
-          name: ${{ needs.validate_tag.outputs.version }}
+          name: ${{ steps.set_attributes.outputs.release_name }}
           tag: v${{ needs.validate_tag.outputs.version }}
           artifacts: cactbot-${{ needs.validate_tag.outputs.version }}.zip
           artifactContentType: application/zip
-          draft: false
+          draft: ${{ steps.set_attributes.outputs.release_draft }}
           generateReleaseNotes: true
 
   create_npm_package:
